Repository awslabs/amazon-eks-ami, pull requests merged in 2022-08, with the labels that each got.

#794 Update Readme file to have clear instructions about how to build usin…
  README.md
Labels: need-code

#964 Extend support for containerd log collecting
  log-collector-script/linux/eks-log-collector.sh
Labels: enhancement

#992 Update container-runtime package versions
  eks-worker-al2.json
Labels: maintenance

#997 Adds section to README on configuring kubelet config
  README.md
Labels: documentation

#1003 Update SSM CreateDocument example for AWSCLI v2.
  log-collector-script/linux/README.md
Labels: documentation

#1000 New instances support
  files/eni-max-pods.txt
Labels: instance-type

#1001 Include source AMI details in tags and manifest
  eks-worker-al2.json
Labels: enhancement
