Repository awslabs/amazon-eks-ami, pull requests merged in 2025-04, with the labels that each got.

#2211 feat(bot): add /clear command
  .github/actions/bot/index.js
Labels: changelog/exclude

#2213 fix(bot): comments response handling
  .github/actions/bot/index.js
Labels: changelog/exclude

#2207 build(al2023): bump nvidia 570 driver and use 6.12 kernel in 1.30+
  templates/al2023/provisioners/install-nvidia-driver.sh
  templates/al2023/variables-1.25.json
  templates/al2023/variables-1.26.json
  templates/al2023/variables-1.27.json
  templates/al2023/variables-1.28.json
  templates/al2023/variables-1.29.json
  templates/al2023/variables-default.json
Labels: kernel, maintenance, gpu

#2208 build(al2023): install nvidia container toolkit from cuda repo
  templates/al2023/provisioners/install-nvidia-driver.sh
Labels: maintenance, gpu
